# Precidtion of Condition Based on Reviews Using Naive Bayes, SVM, Random Forest

In [276]:
# Packages

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [277]:
# Loading the cleaned data

data = pd.read_csv('C:\\Users\\hites\\Downloads\\cleaned.csv')

# Subset Data for top 10 conditions and their reviews to predict condition based on reviews for these top 10 conditions

In [278]:
# Getting the conditions along with their count of occurence in the dataset

con_top_rev = dict(data['condition'].value_counts())

In [279]:
# Selecting the top 10 conditions based on the count

condtn_top_rev = list(con_top_rev.keys())[0:10]

In [280]:
# Grouping the reviews of the top 10 conditions found above to create a subset of data

cntn_rev = dict(data.groupby(['condition'])['review'].value_counts())

In [281]:
# Creating pandas dataframe consisting of conditions along with their reviews

cls_df_rev = pd.DataFrame(cntn_rev.keys(),columns=['Condition','review'])

In [282]:
# Creating pandas dataframe consisting of only top 10 conditions along with their reviews by filtering other conditions

clas_df_rev = cls_df_rev[cls_df_rev.Condition.isin(condtn_top_rev)]

In [283]:
clas_df_rev.shape

(50104, 2)

# Stemming the data for further processing

In [312]:
import nltk.stem

english_stemmer = nltk.stem.SnowballStemmer('english')

In [313]:
def stem_sentences(sentence):
    tokens = sentence.split()
    stemmed_tokens = [english_stemmer.stem(token) for token in tokens]
    return ' '.join(stemmed_tokens)

In [314]:
clas_df_rev['review'] = clas_df_rev['review'].apply(stem_sentences)


C:\Users\hites\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [42]:
#clas_df_rev.to_csv('abc.csv')

# Hold out test for various Algorithms

In [343]:
# Data Assigning for train data
y_train=clas_df_rev['Condition'].values
X_train=clas_df_rev['review'].values

In [344]:
# Split data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
print(X_train[0])
print(y_train[0])
print(X_test[0])
print(y_test[0])

(40083,) (40083,) (10021,) (10021,)
i ve had my implant for 3 year in april it has prevent pregnanc but the side effect have been aw i ve gain 5 stone in weight i have had huge spot come up all over my bodi but main on my face and neck i ve use everi spot treatment out there includ medic from my doctor i ve had tender breast most of the time and have no energi at all i ve spent the last 3 year on diet and exercis and even use weight loss pill and the weight will not shift to the ladi that ask about pregnanc after the implant it is possibl to have a healthi pregnanc after it remov i know 2 peopl that have had healthi children sinc i hope you see this and it help i will not be have a replac after my experi with it
Birth Control
have taken tramadol in the past it liter save my life when i was go through sever depress while slowli recov from a traumat injuri my doctor at the time put me on a light dose of tramadol to help with my somber mood i was aliv again nowaday it virtual imposs to ge

In [345]:
# Validation of train data
training_labels = set(y_train)
print(training_labels)
from scipy.stats import itemfreq
training_category_dist = itemfreq(y_train)
print(training_category_dist)

{'Obesity', 'Birth Control', 'Weight Loss', 'Anxiety', 'ADHD', 'Bipolar Disorde', 'Depression', 'Acne', 'Pain', 'Insomnia'}
[['ADHD' 1771]
 ['Acne' 3164]
 ['Anxiety' 3454]
 ['Bipolar Disorde' 2280]
 ['Birth Control' 14531]
 ['Depression' 5067]
 ['Insomnia' 2245]
 ['Obesity' 1979]
 ['Pain' 3517]
 ['Weight Loss' 2075]]


C:\Users\hites\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  """


In [346]:
# Vectorization

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


#  unigram boolean vectorizer
unigram_bool_vectorizer = CountVectorizer(encoding='latin-1', binary=True, min_df=10,stop_words='english')

#  unigram term frequency vectorizer
unigram_count_vectorizer = CountVectorizer(encoding='latin-1', binary=False, min_df=5,stop_words='english')

#  unigram and bigram term frequency vectorizer
gram12_count_vectorizer = CountVectorizer(encoding='latin-1', ngram_range=(1,2), min_df=5,stop_words='english')

#  unigram tfidf vectorizer
unigram_tfidf_vectorizer = TfidfVectorizer(encoding='latin-1', use_idf=True,ngram_range=(1,2) ,min_df=5,stop_words='english')


In [347]:
# Vectorize the train data 

X_fit = gram12_count_vectorizer.fit(X_train)
X_transform = X_fit.transform(X_train)
X_train_vec = gram12_count_vectorizer.fit_transform(X_train)

# check the content of a document vector
print(X_train_vec.shape)
print(X_train_vec[0].toarray())

# check the size of the constructed vocabulary
print(len(gram12_count_vectorizer.vocabulary_))

# print out the first 10 items in the vocabulary
print(list(gram12_count_vectorizer.vocabulary_.items())[:50])
# check word index in vocabulary
print(gram12_count_vectorizer.vocabulary_)

(40083, 56619)
[[0 0 0 ... 0 0 0]]
56619
[('ve', 51912), ('implant', 25182), ('year', 55965), ('april', 5042), ('prevent', 39421), ('pregnanc', 38903), ('effect', 16775), ('aw', 5492), ('gain', 20859), ('stone', 46470), ('weight', 54028), ('huge', 24755), ('spot', 45437), ('come', 10165), ('bodi', 8155), ('main', 30379), ('face', 18915), ('neck', 33819), ('use', 51379), ('everi', 17924), ('treatment', 50442), ('includ', 25351), ('medic', 31068), ('doctor', 14876), ('tender', 48328), ('breast', 8590), ('time', 49216), ('energi', 17632), ('spent', 45379), ('diet', 14299), ('exercis', 18319), ('loss', 29669), ('pill', 37764), ('shift', 43489), ('ladi', 27394), ('ask', 5151), ('possibl', 38650), ('healthi', 23293), ('remov', 41643), ('know', 27206), ('peopl', 36968), ('children', 9703), ('sinc', 43774), ('hope', 24078), ('help', 23497), ('replac', 41734), ('experi', 18451), ('ve implant', 52086), ('implant year', 25241), ('prevent pregnanc', 39429)]
{'ve': 51912, 'implant': 25182, 'year': 

In [290]:
# Vocabulary of words

vocab = list(gram12_count_vectorizer.vocabulary_.keys())

In [291]:
vocab

['ve',
 'great',
 'results',
 'medication',
 'effects',
 'listed',
 'dry',
 'mouth',
 'numbness',
 'toes',
 'used',
 'properly',
 'help',
 'loose',
 'weight',
 'aid',
 'journey',
 'best',
 'friends',
 'quot',
 'feels',
 'like',
 'just',
 'ate',
 'thanksgiving',
 'meal',
 'everytime',
 'suffer',
 'migraines',
 'works',
 'qsymia',
 'website',
 'offer',
 'savings',
 'coupon',
 'pharmacy',
 'eat',
 'junk',
 'month',
 'hope',
 'lots',
 'won',
 'happen',
 'healthier',
 'medicine',
 'good',
 'luck',
 've great',
 'great results',
 'results medication',
 'medication effects',
 'effects listed',
 'dry mouth',
 'medication used',
 'used properly',
 'loose weight',
 'best friends',
 'feels like',
 'like just',
 'just ate',
 'medication suffer',
 'suffer migraines',
 'medication works',
 'pharmacy just',
 'just eat',
 'eat junk',
 'month hope',
 'lots weight',
 'weight won',
 'won happen',
 'eat medicine',
 'medicine help',
 'help good',
 'good luck',
 'effective',
 'right',
 'bed',
 'did',
 'ende

In [348]:
# Summing the words frequencies in a row
sum_words = X_transform.sum(axis=0)

In [349]:
# Words from Vectorizers along with the frequency of their occurence

words_freq = [(word, sum_words[0, idx]) for word, idx in X_fit.vocabulary_.items()]
sorted(words_freq, key = lambda x: x[1],reverse=True)

[('month', 23348),
 ('day', 22753),
 ('year', 17501),
 ('week', 16979),
 ('start', 16614),
 ('effect', 16429),
 ('ve', 15583),
 ('period', 15162),
 ('feel', 14676),
 ('work', 14529),
 ('pill', 13818),
 ('time', 12951),
 ('pain', 12622),
 ('onli', 12266),
 ('like', 12210),
 ('just', 11204),
 ('weight', 11085),
 ('veri', 11049),
 ('tri', 10155),
 ('use', 9761),
 ('help', 9515),
 ('depress', 9399),
 ('becaus', 9285),
 ('control', 8821),
 ('anxieti', 8686),
 ('acn', 8429),
 ('gain', 8169),
 ('medic', 8154),
 ('got', 8043),
 ('doctor', 7792),
 ('befor', 7647),
 ('sleep', 7535),
 ('sinc', 7371),
 ('birth', 7360),
 ('don', 7291),
 ('realli', 7247),
 ('birth control', 7049),
 ('did', 7040),
 ('bad', 7019),
 ('ani', 6855),
 ('cramp', 6547),
 ('stop', 6528),
 ('life', 6454),
 ('mood', 5944),
 ('great', 5892),
 ('good', 5702),
 ('everi', 5668),
 ('took', 5626),
 ('medicin', 5584),
 ('quot', 5538),
 ('night', 5514),
 ('didn', 5513),
 ('better', 5477),
 ('felt', 5470),
 ('thing', 5465),
 ('went', 5

In [350]:
# Vectorize the test data

X_test_vec = gram12_count_vectorizer.transform(X_test)


# Multinomial Naive Bayes Hold Out Test

In [351]:
# import the MNB module
from sklearn.naive_bayes import MultinomialNB

# initialize the MNB model
nb_clf= MultinomialNB()

# using the training data to train the MNB model
nb_clf.fit(X_train_vec,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [352]:
# For 1 specific condition most popular words
feature_ranks = sorted(zip(nb_clf.coef_[1], gram12_count_vectorizer.get_feature_names()))
category_features = feature_ranks[-20:]
print(category_features)

[(-5.777568546266006, 'realli'), (-5.76007538881849, 'like'), (-5.725981177475513, 'time'), (-5.679054946744144, 'effect'), (-5.6230817884654964, 'dri'), (-5.588407685821811, 'just'), (-5.525208912768442, 'onli'), (-5.414560756018828, 'tri'), (-5.337417880169952, 've'), (-5.253188146142199, 'work'), (-5.229107175148931, 'day'), (-5.216273496810864, 'year'), (-5.112457797929345, 'clear'), (-5.090912978942569, 'start'), (-5.070402444526731, 'week'), (-4.955459219737129, 'face'), (-4.656849481816867, 'use'), (-4.608552617007928, 'month'), (-4.399840180516309, 'skin'), (-4.1047692758673495, 'acn')]


In [353]:
# Most informative features for a class
def show_most_and_least_informative_features(vectorizer, clf, class_idx=0, n=10):
    feature_names = vectorizer.get_feature_names()
    coefs_with_fns = sorted(zip(clf.coef_[class_idx], feature_names))
    top = zip(coefs_with_fns[:n], coefs_with_fns[-n:])
    for (coef_1, fn_1), (coef_2, fn_2) in top:
        print("\t%.4f\t%-15s\t\t%.4f\t%-15s" % (coef_1, fn_1, coef_2, fn_2))

In [354]:
# show most positive features (category 4)
show_most_and_least_informative_features(gram12_count_vectorizer, nb_clf, class_idx=1, n=60)

	-12.5228	00 00          		-6.4429	night          
	-12.5228	00 30          		-6.4360	didn           
	-12.5228	00 month       		-6.4338	break          
	-12.5228	00 pm          		-6.4247	feel           
	-12.5228	000 calori     		-6.4247	pain           
	-12.5228	000 step       		-6.4091	cystic acn     
	-12.5228	00pm           		-6.4003	make           
	-12.5228	06             		-6.3264	notic          
	-12.5228	0mg            		-6.3264	sever          
	-12.5228	10 00          		-6.3182	ani            
	-12.5228	10 11          		-6.2864	don            
	-12.5228	10 13          		-6.2671	look           
	-12.5228	10 15lbs       		-6.2518	better         
	-12.5228	10 16          		-6.2518	doctor         
	-12.5228	10 17          		-6.2056	epiduo         
	-12.5228	10 2014        		-6.1931	stop           
	-12.5228	10 2015        		-6.1860	cream          
	-12.5228	10 2017        		-6.1807	recommend      
	-12.5228	10 20mg        		-6.1807	result         
	-12.5228	10 27          		-6.1

In [355]:
# testing the classifier on the test data set, printing accuracy score

nb_clf.score(X_test_vec,y_test)

0.8438279612813092

In [356]:
# print confusion matrix 

from sklearn.metrics import confusion_matrix
y_pred = nb_clf.fit(X_train_vec, y_train).predict(X_test_vec)
cm=confusion_matrix(y_test, y_pred, labels=['ADHD','Acne','Anxiety','Bipolar Disorde','BirthControl','Depression','Insomnia','Obesity','Pain','Weight Loss'])
print(cm)

[[ 329    1   11    3    0   58    3    3    6    1]
 [   1  694    1    1    0    3    0    2    4    1]
 [   5    0  571   13    0  219   28    2   25    4]
 [   4    2   44  365    0  140   20    4   13    4]
 [   0    0    0    0    0    0    0    0    0    0]
 [   7    2   77   28    0 1031   25    4   22    6]
 [   1    1   27    5    0   30  497    0   12    0]
 [   0    3    5    0    0   12    1  246    2  196]
 [   1    3   16    5    0   27   13    2  839    2]
 [   0    0    3    2    0    8    2  139    2  400]]


In [357]:
# print classification report

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print(precision_score(y_test, y_pred, average=None))
print(recall_score(y_test, y_pred, average=None))

from sklearn.metrics import classification_report
target_names = ['ADHD','Acne','Anxiety','Bipolar Disorde','BirthControl','Depression','Insomnia','Obesity','Pain','Weight Loss']
print(classification_report(y_test, y_pred, target_names=target_names))

[0.9454023  0.91556728 0.74836173 0.86084906 0.96243094 0.66132136
 0.83952703 0.60740741 0.89828694 0.64724919]
[0.78520286 0.88974359 0.65182648 0.6053068  0.96885428 0.84577523
 0.85689655 0.52452026 0.91294886 0.71428571]
                 precision    recall  f1-score   support

           ADHD       0.95      0.79      0.86       419
           Acne       0.92      0.89      0.90       780
        Anxiety       0.75      0.65      0.70       876
Bipolar Disorde       0.86      0.61      0.71       603
   BirthControl       0.96      0.97      0.97      3596
     Depression       0.66      0.85      0.74      1219
       Insomnia       0.84      0.86      0.85       580
        Obesity       0.61      0.52      0.56       469
           Pain       0.90      0.91      0.91       919
    Weight Loss       0.65      0.71      0.68       560

       accuracy                           0.84     10021
      macro avg       0.81      0.78      0.79     10021
   weighted avg       0.85     

In [358]:
## finding the calculated posterior probability
posterior_probs = nb_clf.predict_proba(X_test_vec)

## finding the posterior probabilities for the first test example
print(posterior_probs[0])

# finding the category prediction for the first test example
y_pred = nb_clf.predict(X_test_vec)
print(y_pred[0])

# checking the actual label for the first test example
print(y_test[0])

[1.18076491e-19 6.96468191e-24 1.35075561e-06 1.42035274e-11
 2.63587577e-25 9.99998608e-01 4.18768274e-15 1.18033516e-28
 4.07560440e-08 4.01854255e-31]
Depression
Depression


# Bernoulli Naive Bayes Hold Out Test

In [359]:
# Initializing the BNB model and using the training data to train the BNB model

from sklearn.naive_bayes import BernoulliNB
X_train_vec_bool = unigram_bool_vectorizer.fit_transform(X_train)
be_clf = BernoulliNB()
bernoulliNB_clf = be_clf.fit(X_train_vec_bool, y_train)

In [360]:
# Vectorize the test data using boolean input for Bernoulli

X_test_vec_bol = unigram_bool_vectorizer.transform(X_test)

In [361]:
# testing the classifier on the test data set, printing accuracy score

bernoulliNB_clf.score(X_test_vec_bol,y_test)

0.8255663107474304

In [362]:
# Most informative and least informative features for a specific condition helping in prediction of condition 

show_most_and_least_informative_features(unigram_bool_vectorizer, be_clf, class_idx=1, n=40)

	-8.0602	00pm           		-1.8740	medic          
	-8.0602	06             		-1.8577	cystic         
	-8.0602	103            		-1.8376	result         
	-8.0602	105lbs         		-1.8357	product        
	-8.0602	106            		-1.8278	went           
	-8.0602	108            		-1.8239	breakout       
	-8.0602	10am           		-1.8219	everi          
	-8.0602	10lb           		-1.8064	did            
	-8.0602	10mgs          		-1.7968	recommend      
	-8.0602	10pm           		-1.7705	dermatologist  
	-8.0602	10yr           		-1.7467	got            
	-8.0602	112            		-1.7449	wors           
	-8.0602	115            		-1.7269	help           
	-8.0602	117            		-1.7216	prescrib       
	-8.0602	11am           		-1.6517	sinc           
	-8.0602	11pm           		-1.6289	becaus         
	-8.0602	1200           		-1.6129	pimpl          
	-8.0602	1200mg         		-1.5741	veri           
	-8.0602	120lbs         		-1.5367	befor          
	-8.0602	120mg          		-1.5367	realli         


In [363]:
# print confusion matrix (row: ground truth; col: prediction)

from sklearn.metrics import confusion_matrix
y_pred = bernoulliNB_clf.fit(X_train_vec, y_train).predict(X_test_vec)
cm=confusion_matrix(y_test, y_pred, labels=['ADHD','Acne','Anxiety','Bipolar Disorde','BirthControl','Depression','Insomnia','Obesity','Pain','Weight Loss'])
print(cm)

[[ 252    0   16    1    0   92    3    1   53    1]
 [   1  659    1    0    0    4    0    1   33    0]
 [   4    0  510    5    0  220   25    1  108    0]
 [   0    1   36  287    0  182   13    1   77    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   4    0   60    8    0 1002   19    2  112    2]
 [   0    1   23    3    0   33  434    0   85    0]
 [   0    1    2    0    0   30    2  221   38  163]
 [   0    1    8    2    0   17    6    0  881    2]
 [   0    0    7    1    0   25    1  151   23  342]]


In [364]:
# print classification report

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print(precision_score(y_test, y_pred, average=None))
print(recall_score(y_test, y_pred, average=None))

from sklearn.metrics import classification_report
target_names = ['ADHD','Acne','Anxiety','Bipolar Disorde','BirthControl','Depression','Insomnia','Obesity','Pain','Weight Loss']
print(classification_report(y_test, y_pred, target_names=target_names))

[0.96551724 0.94142857 0.76461769 0.93181818 0.96526813 0.61397059
 0.86282306 0.58311346 0.60383825 0.66666667]
[0.60143198 0.84487179 0.58219178 0.47595357 0.96607341 0.82198523
 0.74827586 0.47121535 0.95865071 0.61071429]
                 precision    recall  f1-score   support

           ADHD       0.97      0.60      0.74       419
           Acne       0.94      0.84      0.89       780
        Anxiety       0.76      0.58      0.66       876
Bipolar Disorde       0.93      0.48      0.63       603
   BirthControl       0.97      0.97      0.97      3596
     Depression       0.61      0.82      0.70      1219
       Insomnia       0.86      0.75      0.80       580
        Obesity       0.58      0.47      0.52       469
           Pain       0.60      0.96      0.74       919
    Weight Loss       0.67      0.61      0.64       560

       accuracy                           0.80     10021
      macro avg       0.79      0.71      0.73     10021
   weighted avg       0.83     

# MNB and BNB Cross Validation

In [365]:
# cross validation MNB TF Input Count Vectorizer

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
nb_clf_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1', binary=False, min_df=5,ngram_range=(1,2),stop_words='english')),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X_train, y_train, cv=10)
avg=sum(scores)/len(scores)
print(avg)

0.8409337626154741


In [341]:
##Bernoulli with Boolean Input
bNB_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1',binary=False)),('bernNB',BernoulliNB())])
scores = cross_val_score(bNB_pipe,X_train,y_train,cv=3)
print(sum(scores)/len(scores))

##MNB TFIDF Vectorizer and TFIDF Input
mNB_tfidf_pipe = Pipeline([('nb_tf',TfidfVectorizer(encoding='latin-1',use_idf=True,binary=False,min_df=20,ngram_range=(1,2),stop_words='english')),('nb',MultinomialNB())])
scores = cross_val_score(mNB_tfidf_pipe,X_train,y_train,cv=10)
print(sum(scores)/len(scores))

##MNB TF Input using TFIDF Vectorizer
mNB_tf_pipe = Pipeline([('nb_tf',TfidfVectorizer(encoding='latin-1',use_idf=False,binary=False,min_df=20,ngram_range=(1,2),stop_words='english')),('nb',MultinomialNB())])
scores = cross_val_score(mNB_tf_pipe,X_train,y_train,cv=10)
print(sum(scores)/len(scores))

##MNB with Bool
nb_clf_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1', binary=True,min_df=20,ngram_range=(1,2),stop_words='english')),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe,X_train,y_train, cv=3)
avg=sum(scores)/len(scores)
print(avg)

##MNB with TF Uni and Bigram
nb_clf_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1',binary=False,min_df=5,ngram_range=(1,2),stop_words='english')),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X_train,y_train, cv=3)
avg=sum(scores)/len(scores)
print(avg)

0.7804212889716337
0.7984218841139703
0.7650923943434386
0.8279231099213261
0.8365386701737566


# SVM

In [366]:
# import the LinearSVC module
from sklearn.svm import LinearSVC

# initialize the LinearSVC model
svm_clf = LinearSVC(C=1)

# use the training data to train the model
svm_clf.fit(X_train_vec,y_train)

LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [386]:
# Generating features for a specific condition out of 10 using get feature names

feature_ranks = sorted(zip(svm_clf.coef_[1], gram12_count_vectorizer.get_feature_names()))

In [387]:
# Specific Condition 20 features with their weights that help to see what model has learnt 
condition_category_10 = feature_ranks[-20:]
print("condition category words")
for i in range(0, len(condition_category_10)):
    print(condition_category_10[i])
print()

condition category words
(0.6052896896469809, 'dermatologist')
(0.6207240221354868, 'alreadi work')
(0.623162089013247, 'acn')
(0.6551846330523221, 'start think')
(0.6697134321963734, 'good product')
(0.6703704137833797, 'broke hive')
(0.6882973716923957, 'doryx')
(0.6902315561785357, 'product recommend')
(0.7147560127374966, 'isn great')
(0.7339983725771531, 'help littl')
(0.7372288656062803, 'dont know')
(0.7424571077525057, 'anoth effect')
(0.770081532867004, 'minocyclin')
(0.7735428682511772, 'becaus gain')
(0.8517710378638685, 'happi doctor')
(0.9656520889212944, 'pricey')
(1.0694866308776243, 'accutan')
(1.0860998996531068, 'solodyn')
(1.1711855075258062, 'amaz help')
(1.2407616839887268, 'doxycyclin')



In [388]:
# Getting not specific condition 20 features Ex. Acne in above cell n Not Acne in this cell
not_condition_category_10 = feature_ranks[:20]
print("not condition category")
for i in range(0, len(not_condition_category_10)):
    print(not_condition_category_10[i])
print()

not condition category
(-0.617296054494321, 'skin befor')
(-0.6060821163597542, 'aless')
(-0.5990218625473583, 'insert')
(-0.5506150994586051, 'remov')
(-0.5496156456378801, 'pregnant')
(-0.4992793040241347, 'acn acn')
(-0.4783871505371489, 'lutera')
(-0.47648932495818563, 'use acn')
(-0.4615956465934592, 'patch')
(-0.4504455381659073, 'acn weight')
(-0.4484799843187509, 'zarah')
(-0.4429716204991655, 'acn pimpl')
(-0.44116820887991437, 'insomnia')
(-0.43564975580535426, 'nuvar')
(-0.4120882428888718, 'control gain')
(-0.4062805972115638, 'avian')
(-0.3978695983503603, 'headach acn')
(-0.38244002672564015, 'prone')
(-0.3808104396725774, 'extrem itchi')
(-0.37573793749139756, 'shot')



In [389]:
# testing the classifier on the test data set, printing out the accuracy score
svm_clf.score(X_test_vec,y_test)

0.8191797225825765

In [390]:
# Generating classification Report and Confusion Matrix
from sklearn.metrics import confusion_matrix
y_pred = svm_clf.predict(X_test_vec)
cm=confusion_matrix(y_test, y_pred, labels=['ADHD','Acne','Anxiety','Bipolar Disorde','BirthControl','Depression','Insomnia','Obesity','Pain','Weight Loss'])
print(cm)
print()

from sklearn.metrics import classification_report
target_names = ['ADHD','Acne','Anxiety','Bipolar Disorde','BirthControl','Depression','Insomnia','Obesity','Pain','Weight Loss']
print(classification_report(y_test, y_pred, target_names=target_names))

[[344   0  18   7   0  28   5   3   6   3]
 [  4 677   1   4   0   7   1   1   3   1]
 [ 15   1 592  39   0 155  25   7  25   5]
 [ 13   4  36 405   0  89  17  11  18   2]
 [  0   0   0   0   0   0   0   0   0   0]
 [ 19   5 148  54   0 868  46   4  39  11]
 [  6   3  46   7   0  29 459   3  19   2]
 [  3   1   8   3   0  19   3 257   7 160]
 [ 11   4  23   9   0  33  15   3 814   2]
 [  5   1   8   4   0  10   2 179   6 334]]

                 precision    recall  f1-score   support

           ADHD       0.82      0.82      0.82       419
           Acne       0.89      0.87      0.88       780
        Anxiety       0.67      0.68      0.67       876
Bipolar Disorde       0.75      0.67      0.71       603
   BirthControl       0.96      0.96      0.96      3596
     Depression       0.69      0.71      0.70      1219
       Insomnia       0.79      0.79      0.79       580
        Obesity       0.54      0.55      0.55       469
           Pain       0.86      0.89      0.87       9

# SVM Cross Validation 3 types Boolean, TF, TFIDF

In [ ]:
# Cross validation for LinearSVC using Count Vectorizer TF Input

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
svm_clf = Pipeline([('vect', CountVectorizer(encoding='latin-1', binary=False, min_df=5,stop_words='english')),('svm', LinearSVC(C=0.2, penalty='l1', dual=False))])
scores= cross_val_score(svm_clf, X_train, y_train, cv=5)
print(scores)
avg=sum(scores)/len(scores)
print(avg)

In [ ]:
# Cross validation for LinearSVC using Count Vectorizer Boolean Input

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
svm_clf = Pipeline([('vect', CountVectorizer(encoding='latin-1', binary=True,ngram_range = (1,2), min_df=5,stop_words='english')),('svm', LinearSVC(C=1.5, penalty='l1', dual=False))])
scores= cross_val_score(svm_clf, X_train, y_train, cv=5)
print(scores)
avg=sum(scores)/len(scores)
print(avg)

In [ ]:
# Cross validation for LinearSVC using TFIDF Vectorizer TFIDF Input 

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
svm_clf = Pipeline([('vect', TfidfVectorizer(encoding='latin-1',use_idf=False, binary=False,ngram_range = (1,3), min_df=5,stop_words='english')),('svm', LinearSVC(C=1.5, penalty='l1', dual=False))])
scores= cross_val_score(svm_clf, X_train, y_train, cv=5)
print(scores)
avg=sum(scores)/len(scores)
print(avg)

# Random Forest Cross Validation

In [ ]:
# Random Forest using Count Vectorizer Boolean/TF Input
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
nb_clf_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1',ngram_range = (1,2),binary=True,min_df=20)),('rf', RandomForestClassifier(n_estimators=80,max_depth=10,random_state=0))])
scores = cross_val_score(nb_clf_pipe, X_train, y_train, cv=5)
avg=sum(scores)/len(scores)
print(avg)

In [ ]:
# Random Forest using TFIDF Vectorizer TF/TFIDF Input
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
nb_clf_pipe = Pipeline([('vect', TfidfVectorizer(encoding='latin-1',use_idf=False,ngram_range = (1,2),binary=True,min_df=20)),('rf', RandomForestClassifier(n_estimators=80,max_depth=10,random_state=0))])
scores = cross_val_score(nb_clf_pipe, X_train, y_train, cv=5)
avg=sum(scores)/len(scores)
print(avg)

In [396]:
# import the MNB module
from sklearn.ensemble import RandomForestClassifier

# initialize the MNB model
rf_clf = RandomForestClassifier()

# using the training data to train the MNB model
rf_clf.fit(X_train_vec,y_train)

C:\Users\hites\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [395]:
rf_clf.score(X_test_vec,y_test)

0.37171938928250675